version: '3'
services:
  drupal_db_service:
    container_name: drupal_db
    image: mysql:latest
    ports:
      - "33061:3306"
    environment:
      MYSQL_DATABASE: drupal
      MYSQL_USER: admin
      MYSQL_PASSWORD: 123456
      MYSQL_ROOT_PASSWORD: 123456

  drupal_phpmyadmin_service:
    container_name: drupal_phpmyadmin
    image: phpmyadmin/phpmyadmin
    ports:
      - "8081:80"
    environment:
      PMA_HOST: drupal_db_service
      PMA_PORT: 3306
      MYSQL_ROOT_PASSWORD: 123456
      UPLOAD_LIMIT: 64000M
    depends_on:
      - drupal_db_service

  drupal_service:
    container_name: drupal
    ports:
      - "8441:443"
    depends_on:
      - drupal_db_service
    build: .
    volumes:
      - ../.:/var/www/html
    hostname: drupal-local.com
    networks:
      default:
        aliases:
          - drupal-local.com
