version: '3'
services:
  gutenberg_db_service:
    container_name: gutenberg_db
    image: mysql:latest
    ports:
      - "33061:3306"
    environment:
      MYSQL_DATABASE: gutenberg
      MYSQL_USER: admin
      MYSQL_PASSWORD: 123456
      MYSQL_ROOT_PASSWORD: 123456

  gutenberg_phpmyadmin_service:
    container_name: gutenberg_phpmyadmin
    image: phpmyadmin/phpmyadmin
    ports:
      - "8081:80"
    environment:
      PMA_HOST: gutenberg_db_service
      PMA_PORT: 3306
      MYSQL_ROOT_PASSWORD: 123456
      UPLOAD_LIMIT: 64000M
    depends_on:
      - gutenberg_db_service

  gutenberg_service:
    container_name: gutenberg
    ports:
      - "8441:443"
    depends_on:
      - gutenberg_db_service
    build: .
    volumes:
      - ../.:/var/www/html
    hostname: gutenberg-local.com
    networks:
      default:
        aliases:
          - gutenberg-local.com
